name: localization_table
description: Localize you app the easy way using a localization table.
version: 0.1.2
homepage: https://github.com/ali2236/localization_table

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: